### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by oumbreg** [KeyPharm/Anticansancio-NiNoKuniXW#2]
happening after update
![unknown](https://user-images.githubusercontent.com/97613445/171916107-ca1ec7dc-5f91-4401-9b05-fd648d314bc6.png)

**Comment by oumbreg** [comment]
fixed after updating requirements :) tysm

**Comment by KeyPharm** [comment]
Sorry, I forgot to add the yaml module.
New update push, after you update it run install_all_dependences.bat
Thanks for the error.
